version: '3.1'
services:
 db:
  image: mysql
  environment:
   MYSQL_DATABASE: db_example
   MYSQL_ROOT_PASSWORD: gdn...
  volumes:
   - ./data/mysql:/var/lib/mysql

 redis:
  image: redis
  volumes:
   - ./data/redis:/data

 user-project:
  image: anapsix/alpine-java:8_server-jre_unlimited
  volumes:
   - ./user-spring-boot-starter/target/user-spring-boot-starter-1.0-SNAPSHOT.jar:/app/app.jar
  command: /app/app.jar
  ports:
   - "8081:8080"
  environment:
   - TZ=Asia/Shanghai